### ISSUE TITLE
Have you run into issues with suspend?

### ISSUE THREAD

**Issue by nitsanw** [konklone/ubuntu#3]
I'm in the process of repeating this install process and in the past I've had no luck with Ubuntu suspending correctly. It would pretend to suspend while in fact not shutting down and eating the battery.

**Comment by konklone** [comment]
Huh -- I'm also so in the habit of being burned by suspend in Linux, that I just disable it right away when I install fresh. So I haven't tried it! I'll give it a shot on my Macbook Pro and let you kno

**Comment by konklone** [comment]
Yeah, I just had a bad experience manually suspending my Ubuntu laptop, and then attempting to come back. I couldn't resuscitate it, though I saw a brief flash of screen before it went dark again. So maddening.

It's possible that there's something Macbook-specific about this in its interaction with Ubuntu, but I can't find anything in some light research via Google and the Ubuntu wiki. 

Closing the issue, but very up for re-opening to discuss solutions.
