### ISSUE TITLE
Why do you not use the Mac specific ISO?

### ISSUE THREAD

**Issue by AureliusTech** [konklone/ubuntu#4]
Hi -- Thanks for your tutorial.  Why do you use the generic 15.04 ISO and not use the Mac ISO from Ubuntu?  (Just curious) Thanks!

**Comment by konklone** [comment]
I was (originally) following [these instructions](https://help.ubuntu.com/community/MacBookPro11-1/Saucy), which say:

> The 2013 MacBook Pro can recognize multi-boot CD image (e.g., Ubuntu's official iso). So there is no need to use the "mac" iso image for installation. In fact, I recommend you avoid the "mac" iso image because it is a BIOS-boot only image and will force the Mac to enter BIOS emulation mode to install Ubuntu, which will need to be fixed to boot in its native EFI mode.

I'm not an expert on this stuff myself, so I mostly do what wiki pages tell me. ;)
